language: csharp
dist: trusty
mono:
  - latest
git:
  depth: 300

install:
  - nuget install NUnit.Runners -Version 3.4.0 -OutputDirectory testrunner
script:	
  - bash travis-ci/autoversion.sh SimpleChannel.Net
  - export EnableNuGetPackageRestore=false
  - cert-sync /etc/ssl/certs/ca-certificates.crt
  - travis_retry mono --runtime=v4.0.30319 .nuget/NuGet.exe restore SimpleChannel.Net.sln 
  - xbuild /p:Configuration=Release SimpleChannel.Net.sln
  - xbuild /p:Configuration=Debug SimpleChannel.Net.sln
#  - mono ./testrunner/NUnit.ConsoleRunner.3.4.0/tools/nunit3-console.exe -framework=4.0 ./SimpleChannel.Net.Tests/bin/Debug/SimpleChannel.Net.Tests.dll
  - travis_retry bash travis-ci/nuget-upload.sh