language: csharp
sudo: false
dist: trusty
mono:
  - latest
git:
  depth: 300
addons:
  apt:
    packages:
     - realpath

install:
  - nuget install NUnit.Runners -Version 3.4.0 -OutputDirectory testrunner
script:	
  - bash travis-ci/autoversion.sh SimpleChannel.Net
  - export EnableNuGetPackageRestore=false
  - cert-sync /etc/ssl/certs/ca-certificates.crt
  - travis_retry mono --runtime=v4.0.30319 .nuget/NuGet.exe restore SimpleChannel.Net.sln 
  - xbuild CI.proj
  - mono ./testrunner/NUnit.Runners.3.4.0/tools/nunit-console.exe -framework=4.0 ./SimpleChannel.Net.Tests/bin/Debug/SimpleChannel.Net.Tests.dll -exclude Integration,NotWorkingOnMono
  - travis_retry bash travis-ci/nuget-upload.sh