language: csharp
sudo: required
dist: trusty
mono:
  - latest
git:
  depth: 300
  
script:	
  - bash travis-ci/autoversion.sh SimpleChannel.Net
  - export EnableNuGetPackageRestore=false
  - cert-sync /etc/ssl/certs/ca-certificates.crt
  - travis_retry mono --runtime=v4.0.30319 .nuget/NuGet.exe restore SimpleChannel.Net.sln 
  - xbuild CI.proj
  - sudo nunit-console -framework=4.0 ./SimpleChannel.Net.Tests/bin/Debug/SimpleChannel.Net.Tests.dll -exclude Integration,NotWorkingOnMono
  - travis_retry bash travis-ci/nuget-upload.sh